In [1]:
import numpy as np
import unittest
from sklearn import datasets
import sys  
sys.path.append('../')
from util import import_notebook
from util.data_process import *

importing Jupyter notebook from ../util/data_process.ipynb


In [2]:
class Test_data_process(unittest.TestCase):
    
    def test_dummy(self):
        y = np.array([0, 1, 2, 3])
        y_dummy = dummy(y, 4)
        msg = "elements in array are not equal"
        self.assertListEqual(y_dummy[0].tolist(), [1, 0, 0, 0], msg)
        self.assertListEqual(y_dummy[1].tolist(), [0, 1, 0, 0], msg)
        self.assertListEqual(y_dummy[2].tolist(), [0, 0, 1, 0], msg)
        self.assertListEqual(y_dummy[3].tolist(), [0, 0, 0, 1], msg)
        
    def test_inv_dummy(self):
        y = np.array([[0, 1, 0],
                      [1, 0, 0],
                      [0, 1, 0],
                      [0, 0, 1],
                      [0, 0, 0]])
        y_inv = inv_dummy(y)
        msg = "elements in array are not equal"
        self.assertListEqual(y_inv.tolist(), [1, 0, 1, 2, 3], msg)
        
    def test_dummy(self):
        y = np.array([0, 1, 2, 3])
        y_dummy = dummy(y, 4)
        msg = "elements in array are not equal"
        self.assertListEqual(y_dummy[0].tolist(), [1, 0, 0, 0], msg)
        self.assertListEqual(y_dummy[1].tolist(), [0, 1, 0, 0], msg)
        self.assertListEqual(y_dummy[2].tolist(), [0, 0, 1, 0], msg)
        self.assertListEqual(y_dummy[3].tolist(), [0, 0, 0, 1], msg)
    
    def test_split_data(self):
        x = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5]])
        y = np.array([0, 1, 2, 3])
        print(split_data(x))
        print(split_data(x, y))
        print(split_data(x, y, ratio=[0.5, 0.25]))
        
        iris = datasets.load_iris()
        data = iris.data[45:55]
        label = iris.target[45:55]
        print(data)
        print(label)
        
        print(split_data(data))
        print(split_data(data, label))
        print(split_data(data, label, ratio=[0.75, 0.25]))

In [3]:
if __name__ == '__main__':
    Test_data_process().test_dummy()
    Test_data_process().test_inv_dummy()
    Test_data_process().test_split_data()

(array([[3, 4],
       [2, 3],
       [4, 5]]), array([[1, 2]]), array([], shape=(0, 2), dtype=int64))
((array([[2, 3],
       [1, 2],
       [4, 5]]), array([1, 0, 3])), (array([[3, 4]]), array([2])), (array([], shape=(0, 2), dtype=int64), array([], dtype=int64)))
((array([[2, 3],
       [3, 4]]), array([1, 2])), (array([[1, 2]]), array([0])), (array([[4, 5]]), array([3])))
[[4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
[0 0 0 0 0 1 1 1 1 1]
(array([[5.5, 2.3, 4. , 1.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [5.3, 3.7, 1.5, 0.2]]), array([[4.8, 3. , 1.4, 0.3]]), array([[6.5, 2.8, 4.6, 1.5]]))
((array([[6.4, 3.2, 4.5, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.8, 3. , 1.4, 